version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: postgres-flight
    environment:
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: flightroutes
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - flight-network

  redis:
    image: redis:latest
    container_name: redis-flight
    ports:
      - "6379:6379"
    networks:
      - flight-network

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: flight-app
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: test
    ports:
      - "8080:8080"
    networks:
      - flight-network

networks:
  flight-network:
    driver: bridge

volumes:
  postgres-data: