-- we don't know how to generate root <with-no-name> (class Root) :(


CREATE TABLE locations
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255)                            NOT NULL,
    country       VARCHAR(255)                            NOT NULL,
    city          VARCHAR(255)                            NOT NULL,
    location_code VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_locations PRIMARY KEY (id)
);

CREATE TABLE transportation_operating_days
(
    transportation_id BIGINT NOT NULL,
    operating_days    INTEGER
);

CREATE TABLE transportations
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    origin_location_id      BIGINT                                  NOT NULL,
    destination_location_id BIGINT                                  NOT NULL,
    transportation_type     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_transportations PRIMARY KEY (id)
);

CREATE TABLE "user"
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    role     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE locations
    ADD CONSTRAINT uc_locations_location_code UNIQUE (location_code);

ALTER TABLE "user"
    ADD CONSTRAINT uc_user_username UNIQUE (username);

ALTER TABLE transportations
    ADD CONSTRAINT FK_TRANSPORTATIONS_ON_DESTINATION_LOCATION FOREIGN KEY (destination_location_id) REFERENCES locations (id);

ALTER TABLE transportations
    ADD CONSTRAINT FK_TRANSPORTATIONS_ON_ORIGIN_LOCATION FOREIGN KEY (origin_location_id) REFERENCES locations (id);

ALTER TABLE transportation_operating_days
    ADD CONSTRAINT fk_transportation_operating_days_on_transportation FOREIGN KEY (transportation_id) REFERENCES transportations (id);